MBCS_MFC_Debug\Markup.exe -autoexit
MBCS_MFC_STDCONV_Debug\Markup.exe -autoexit
MBCS_MFC_Release\Markup.exe -autoexit
MBCS_MFC_STDCONV_Release\Markup.exe -autoexit
MBCS_STL_Debug\Markup.exe -autoexit
MBCS_STL_STDCONV_Debug\Markup.exe -autoexit
MBCS_STL_Release\Markup.exe -autoexit
MBCS_STL_STDCONV_Release\Markup.exe -autoexit
MFC_Debug\Markup.exe -autoexit
MFC_STDCONV_Debug\Markup.exe -autoexit
MFC_Release\Markup.exe -autoexit
MFC_STDCONV_Release\Markup.exe -autoexit
MSXML_Debug\Markup.exe -autoexit
MSXML_Release\Markup.exe -autoexit
STL_Debug\Markup.exe -autoexit
STL_STDCONV_Debug\Markup.exe -autoexit
STL_Release\Markup.exe -autoexit
STL_STDCONV_Release\Markup.exe -autoexit
Unicode_MFC_Debug\Markup.exe -autoexit
Unicode_MFC_STDCONV_Debug\Markup.exe -autoexit
Unicode_MFC_Release\Markup.exe -autoexit
Unicode_MFC_STDCONV_Release\Markup.exe -autoexit
Unicode_MSXML_Debug\Markup.exe -autoexit
Unicode_MSXML_Release\Markup.exe -autoexit
Unicode_STL_Debug\Markup.exe -autoexit
Unicode_STL_STDCONV_Debug\Markup.exe -autoexit
Unicode_STL_Release\Markup.exe -autoexit
Unicode_STL_STDCONV_Release\Markup.exe -autoexit

